language: php

php:
  - 7.1
  - 7.2

env:
  - setup=stable
  - setup=lowest

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script:
  - vendor/bin/phpunit
