<?php

namespace JdPowered\Geofox\Enum;

class AttributeType extends Enum
{
    const ACCURATE = 'ACCURATE';
    const ANNOUNCEMENT = 'ANNOUNCEMENT';
    const DIRECTION_NAME = 'DIRECTION_NAME';
    const DISPOSITIVE_ACTION = 'DISPOSITIVE_ACTION';
    const ENTRY_PROHIBITED = 'ENTRY_PROHIBITED';
    const MISSING_UPDATE = 'MISSING_UPDATE';
    const NOCHANGE = 'NOCHANGE';
    const NORMAL = 'NORMAL';
    const PLATFORM = 'PLATFORM';
    const POSITION_BACK = 'POSITION_BACK';
    const POSITION_FRONT = 'POSITION_FRONT';
    const POSITION_MIDDLE = 'POSITION_MIDDLE';
    const REALTIME = 'REALTIME';
    const STOP_ON_DEMAND = 'STOP_ON_DEMAND';
    const TECHNICAL_PROBLEM = 'TECHNICAL_PROBLEM';
    const TRAFFIC_JAM = 'TRAFFIC_JAM';
}
